# Convolutional Neural Network

In [1]:
# Importing the libraries
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator
print(tf.__version__)
import numpy as np
from keras.preprocessing import image

2.3.0


## Part 1 - Data Preprocessing

In [2]:
# Preprocessing the Training set
train_datagen = ImageDataGenerator(
        rescale=1./255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True)
training_set = train_datagen.flow_from_directory(
        'dataset/training_set',
        target_size=(64, 64),  # make training much faster
        batch_size=32,  # how many images in each batch, 32 is a classic default
        class_mode='binary')  # cat, dog: binary

# Preprocessing the Test set
test_datagen = ImageDataGenerator(rescale=1./255)
test_set = test_datagen.flow_from_directory(
        'dataset/test_set',
        target_size=(64, 64),
        batch_size=32,
        class_mode='binary')

Found 8000 images belonging to 2 classes.
Found 2000 images belonging to 2 classes.


## Part 2 - Building the CNN

In [3]:
# Initialising the CNN
cnn = tf.keras.models.Sequential()  # an object as sequence of layers

# Step 1 - Convolution, use add method to add layer
cnn.add(tf.keras.layers.Conv2D(filters=32,
                              kernel_size=3,
                              activation='relu',
                              input_shape=[64, 64, 3]))

# Step 2 - Pooling (Max Pooling)
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

# Adding a second convolutional layer
cnn.add(tf.keras.layers.Conv2D(filters=32,
                               kernel_size=3,
                               activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

# Step 3 - Flattening
cnn.add(tf.keras.layers.Flatten())

# # Step 4 - Full Connection
cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))

# Step 5 - Output Layer
cnn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the CNN

In [4]:
# Compiling the CNN
cnn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Training the CNN on the Training set and evaluating it on the Test set
cnn.fit(x=training_set, validation_data=test_set, epochs=25)

Epoch 1/25
250/250 [==============================] - 40s 160ms/step - loss: 0.6718 - accuracy: 0.5755 - val_loss: 0.6259 - val_accuracy: 0.6590
Epoch 2/25
250/250 [==============================] - 42s 167ms/step - loss: 0.6041 - accuracy: 0.6725 - val_loss: 0.6049 - val_accuracy: 0.6775
Epoch 3/25
250/250 [==============================] - 39s 157ms/step - loss: 0.5519 - accuracy: 0.7207 - val_loss: 0.5790 - val_accuracy: 0.7040
Epoch 4/25
250/250 [==============================] - 39s 155ms/step - loss: 0.5127 - accuracy: 0.7455 - val_loss: 0.5924 - val_accuracy: 0.7170
Epoch 5/25
250/250 [==============================] - 35s 142ms/step - loss: 0.4952 - accuracy: 0.7596 - val_loss: 0.5154 - val_accuracy: 0.7490
Epoch 6/25
250/250 [==============================] - 38s 153ms/step - loss: 0.4753 - accuracy: 0.7715 - val_loss: 0.5537 - val_accuracy: 0.7430
Epoch 7/25
250/250 [==============================] - 41s 162ms/step - loss: 0.4663 - accuracy: 0.7751 - val_loss: 0.5517 - val_ac

## Part 4 - Making a single prediction

In [17]:
test_image = image.load_img('dataset/single_prediction/cat_or_dog_1.jpg', target_size=(64, 64))
test_image = image.img_to_array(test_image)
print("Array", test_image)
test_image = np.expand_dims(test_image, axis=0)
print("Vector", test_image)
result = cnn.predict(test_image)
print(training_set.class_indices)

# Encoding to specify which is 1 and which is 0
if result[0][0] == 1:
    prediction = 'dog'
else:
    prediction = 'cat'
print("Single Prediction: ", prediction)

Array [[[ 54.  58.   7.]
  [ 58.  63.   9.]
  [ 64.  67.  10.]
  ...
  [136. 144.  71.]
  [140. 150.  77.]
  [139. 149.  78.]]

 [[ 48.  54.   6.]
  [ 51.  58.   7.]
  [ 58.  63.   9.]
  ...
  [129. 137.  64.]
  [139. 149.  78.]
  [141. 151.  80.]]

 [[ 48.  56.   7.]
  [ 48.  56.   7.]
  [ 54.  61.  10.]
  ...
  [123. 130.  63.]
  [136. 145.  80.]
  [140. 149.  82.]]

 ...

 [[ 46.  55.  12.]
  [ 42.  50.   9.]
  [ 38.  49.   9.]
  ...
  [239. 205. 170.]
  [235. 209. 186.]
  [229. 202. 173.]]

 [[ 50.  57.  15.]
  [ 42.  50.   9.]
  [ 44.  52.  11.]
  ...
  [234. 200. 162.]
  [236. 206. 178.]
  [234. 203. 174.]]

 [[ 53.  59.  13.]
  [ 43.  51.  10.]
  [ 49.  56.  12.]
  ...
  [231. 195. 159.]
  [235. 213. 190.]
  [233. 206. 179.]]]
Vector [[[[ 54.  58.   7.]
   [ 58.  63.   9.]
   [ 64.  67.  10.]
   ...
   [136. 144.  71.]
   [140. 150.  77.]
   [139. 149.  78.]]

  [[ 48.  54.   6.]
   [ 51.  58.   7.]
   [ 58.  63.   9.]
   ...
   [129. 137.  64.]
   [139. 149.  78.]
   [141. 151.

In [18]:
test_image = image.load_img('dataset/single_prediction/cat_or_dog_2.jpg', target_size=(64, 64))

test_image = np.expand_dims(test_image, axis=0)

result = cnn.predict(test_image)
print(training_set.class_indices)

# Encoding to specify which is 1 and which is 0
if result[0][0] == 1:
    prediction = 'dog'
else:
    prediction = 'cat'
    
print("Single Prediction: ", prediction)

{'cats': 0, 'dogs': 1}
Single Prediction:  dog


In [19]:
test_image = image.load_img('dataset/single_prediction/cat_or_dog_3.jpg', target_size=(64, 64))
test_image = image.img_to_array(test_image)

test_image = np.expand_dims(test_image, axis=0)

result = cnn.predict(test_image)
print(training_set.class_indices)

# Encoding to specify which is 1 and which is 0
if result[0][0] == 1:
    prediction = 'dog'
else:
    prediction = 'cat'
print("Single Prediction: ", prediction)

{'cats': 0, 'dogs': 1}
Single Prediction:  dog


In [20]:
test_image = image.load_img('dataset/single_prediction/cat_or_dog_4.jpg', target_size=(64, 64))
test_image = image.img_to_array(test_image)

test_image = np.expand_dims(test_image, axis=0)

result = cnn.predict(test_image)
print(training_set.class_indices)

# Encoding to specify which is 1 and which is 0
if result[0][0] == 1:
    prediction = 'dog'
else:
    prediction = 'cat'
print("Single Prediction: ", prediction)

{'cats': 0, 'dogs': 1}
Single Prediction:  cat
